version: 0.0
os: linux
files:
  - source: .
    destination: /home/ec2-user/apps/codedeploy_rails
hooks:
  BeforeInstall:
    - location: scripts/install_and_configure_supervisord.sh
      runas: ec2-user
  AfterInstall:
    - location: scripts/update_permissions.sh
      runas: ec2-user
    - location: scripts/configure_foreman.sh
      runas: ec2-user
    - location: scripts/configure_rails.sh
      runas: ec2-user
  ApplicationStart:
    - location: scripts/start_server.sh
      runas: ec2-user
  ValidateService:
    - location: scripts/validate_service.sh
      runas: ec2-user
  ApplicationStop:
    - location: scripts/stop_server.sh
      runas: ec2-user

